### ISSUE TITLE
Saw this was included in the latest RM release

### ISSUE THREAD

**Issue by mkondel** [devicious/gem-flipperzero#1]
Is this a demo for how to implement UI and user inputs in firmware?

**Comment by RogueMaster** [comment]
I'm not quite sure what it does. Just added it as something else to try and play with 😄 I would love more info if you can @devicious

**Comment by devicious** [comment]
Hello! Nice to hear from you.
I’m really sorry guys, it was not meant to be pushed at all!
As you said it is just the baseline for a plugin idea I’m experimenting with.
Maybe we’ll get back in touch in case it becomes something actually nice. :)
Happy new year,
Wish you best!
Il 31 dic 2022, 19:52 +0100, RogueMaster ***@***.***>, ha scritto:

**Comment by mkondel** [comment]
Happy New Year to all, and welcome to the bleeding edge!
